### ISSUE TITLE
Question: Is it possible to use PunchBoot for i.MX 6UL EVK?

### ISSUE THREAD

**Issue by danie007** [jonasblixt/punchboot#13]
Hey,

I've recently looked at your **PunchBoot** and impressed by the [published boot time](https://github.com/jonasblixt/punchboot#metrics). We're currently working in [i.MX 6UL EVK](https://www.nxp.com/design/development-boards/i-mx-evaluation-and-development-boards/i-mx6ultralite-evaluation-kit:MCIMX6UL-EVK) and wonder how much work is required for porting, sadly I can't find any supporting documents here.
Below are my questions regarding your amazing **PunchBoot**:

1. How boot time is calculated?
2. Are you using HAB in punchboot?
3. How closely **PunchBoot** related to *U-Boot*?
4. Is there any more documents available for porting?

Thanks in advance.

**Comment by jonasblixt** [comment]
Hello and thanks for your interest!

1. Typically measured from de-assertion of the reset-signal until jump to linux-kernel or what ever is supposed to boot.

2. Yes, but mostly for logging. PB uses the crypto hardware (CAAM) directly

3. Not at all

4. Not really, so far this is a one man show and I think it will take a while before those things are in place

Punchboot has mature support for imx6ul but the EVK is not supported (yet), the main issue with the EVK is that it does not have an eMMC populated, which is the only supported memory type so far. I think the best approach to get the EVK working would be to implement a QSPI block-driver. 

I would appreciate any help with this, I would be willing to give some support if you choose to try that.

I've mostly used punchboot for imx6ul on some of my custom hardware, which is also open source, you can find them here:
https://github.com/jonasblixt/jiffy
https://github.com/jonasblixt/bebop

Jonas
